---
- name: 'Deploy gcp disk'
  hosts: localhost
  connection: local
  become: false
  gather_facts: no
  vars:
    gcp_project: "true-campus-327318"
    gcp_cred_kind: "serviceaccount"
    gcp_cred_file: "./user.json"
    gcp_region: "us-central1"
    gcp_zone: "us-central1-a"
    desired_state: "absent" 
 
  tasks:
  - name: create a disk
    google.cloud.gcp_compute_disk:
      name: disk-instance
      size_gb: 50
      source_image: projects/ubuntu-os-cloud/global/images/family/ubuntu-1604-lts
      zone: us-central1-a
      project: "{{ gcp_project }}"
      auth_kind: "{{ gcp_cred_kind }}"
      service_account_file: "{{ gcp_cred_file }}"
      state: "{{ desired_state | default('present') }}"
    register: disk
